### ISSUE TITLE
Enable sticky bezel for flycut recipe

### ISSUE THREAD

**Issue by codeword** [pivotal-sprout/sprout-osx-apps#252]
This allows the user to release cmd+shft+v while they are looking for the correct content.   They can then hit enter to paste it or esc to escape if they cant find it.

**Comment by wendorf** [comment]
Hi @codeword ,

The flycut recipe was removed in #267 . If we were to support this now, we'd probably add back the flycut recipe as one that just installs via homebrew then does additional config (similar to how we install [iterm2](https://github.com/pivotal-sprout/sprout-osx-apps/blob/master/recipes/iterm2.rb)). Do you think this is valuable enough for bringing back a new version of the flycut recipe?

Thanks,
@wendorf

**Comment by wendorf** [comment]
Due to inactivity, I'm going to close this issue. If you'd like to discuss this further, please feel free to re-open or open a new issue.
