### ISSUE TITLE
`sprout-osx-apps::go` should only recompile/install go if it is outdated

### ISSUE THREAD

**Issue by aramprice** [pivotal-sprout/sprout-osx-apps#256]
It appears that go is recompiled regardless of whether it is currently installed or not.

It would be nice if the recipe were able to detect the current version and only recompile/install if it is out of date.

**Comment by wendorf** [comment]
It looks like this is no longer happening with the recipe.

**Comment by aramprice** [comment]
... sadly this seems to cause problems with travis workers because the go package is "smartly" noticing that `go` is present and skipping the `brew install` **but** the travis workers have an old version of golang installed (~1.3) which is not compatible with some source / commands used by teams.

/cc @mmb
