### ISSUE TITLE
how do I update the version of Keycastr in pivotal workstation

### ISSUE THREAD

**Issue by akitchen** [pivotal-sprout/sprout-osx-apps#258]
Hello friends!

How do I update the version of Keycastr in pivotal workstation?  The version we have is way out of date, and doesn't play nice with OS X 10.10 or 10.9.  A few of us have been working on improving it, and I'd love to see those improvements in our sprout'ed workstations.

Please let me know how I can help

Thanks

**Comment by hiremaga** [comment]
Thanks Andrew!

I think the easiest way to maintain this would be as a Homebrew formula.
Where possible we'd like to favor that over recipes in this cookbook.

If you can get a Homebrew formula accepted we can deprecate the
broken recipe in favor of that. Do you think that's work?

If they don't accept the formula upstream there's a pivotal specific tap we
can use.

**Comment by akitchen** [comment]
Thanks @hiremaga I will look into it !
